version: '3.8'

services:

  haproxy:
    image: haproxy
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    # networks:
    #   - default
    #   - proxy
    links:
      - auth:auth
      - ecommerce:ecommerce
      - oms:oms
      
  auth:
    build: ./auth
    environment:
      - SERVER_PORT=5000
    # ports:
    #   - "5000"
  ecommerce:
    build: ./ecommerce
    environment:
      - SERVER_PORT=7000
    # ports:
    #   - "7000"
  oms:
    build: ./oms
    environment:
      - SERVER_PORT=8000
    # ports:
    #   - "8000"
